[project]
name = "pygame_shaders"
version = "2.0.1"
dependencies = ["numpy", "moderngl", "pygame"]
dynamic = ["description", "readme", "authors", "classifiers"]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"